---
- name: install dependencies for Centos 6
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ directadmin_centos6_packages}}"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: install dependencies for Centos 7
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ directadmin_centos7_packages}}"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

