---
- name: update-system
  command: yum update -y

- name: obtain setup.sh script
  get_url:
    url: "{{ directadmin_setup_url }}"
    dest: "{{ directadmin_setup_path }}/"

- name: ensure proper permissions on setup.sh
  file:
    path: "{{ directadmin_setup_path }}/setup.sh"
    mode: 0755

- name: ensure custombuild version is set
  template:
    src: .custombuild.j2
    dest: "{{ directadmin_setup_path }}/.custombuild"

- block:
    - name: ensure directadmin path if remote options file is used
      file:
        path: "{{ directadmin_custombuild_path }}"
        recurse: yes
        state: directory

    - name: try remote custombuild options file
      get_url:
        url: "{{ directadmin_custombuild_options_conf }}"
        dest: "{{ directadmin_custombuild_path }}/options.conf"

  when: directadmin_custombuild_options_conf is defined and directadmin_custombuild_options_conf is not none

# https://sohani.me

- debug:
    msg: "This is a good time for a coffee break - saman-sohani"
  when: directadmin_install

- name: run setup
  command: "{{ directadmin_setup_path }}/setup.sh {{ directadmin_client_id }} {{ directadmin_license_id }} {{ directadmin_hostname }} {{ directadmin_ethernet_device }} {{ directadmin_ip_address | default( hostvars[inventory_hostname]['ansible_' + directadmin_ethernet_device]['ipv4']['address'] ) }}"
  register: setup_output
  when: directadmin_install

- name: directadmin
  command: /usr/local/directadmin/directadmin i

- debug:
    var: setup_output.stdout_lines
  when: directadmin_install

- debug:
    msg: "Directadmin is already installed and running, skipping.."
  when: not directadmin_install

