---
- name: yum Update
  yum: name=* state=latest
  tags: [yum_update]

- name: "Set up prerequisites file"
  copy:
    content: 1
    dest: /root/.preinstall
    force: no
    group: root
    owner: root
    mode: 644

- name: obtain setup.sh script
  get_url:
    url: "{{ directadmin_setup_url }}"
    dest: "{{ directadmin_setup_path }}/"

- name: ensure proper permissions on setup.sh
  file:
    path: "{{ directadmin_setup_path }}/setup.sh"
    mode: 0755

- name: "Set installer permissions"
  file:
    path: /root/setup.sh
    mode: 755

- name: "Set up custombuild version"
  copy:
    content: "2.0"
    dest: /root/.custombuild
    force: no
    mode: 644

# https://sohani.me

- debug:
    msg: "This is a good time for a coffee break - sohani.me"
  when: directadmin_install

- name: run setup
  command: "{{ directadmin_setup_path }}/setup.sh {{ directadmin_client_id }} {{ directadmin_license_id }} {{ directadmin_hostname }} {{ directadmin_ethernet_device }} {{ directadmin_ip_address | default( hostvars[inventory_hostname]['ansible_' + directadmin_ethernet_device]['ipv4']['address'] ) }}"
  register: setup_output
  when: directadmin_install

- name: Remove conf file
  shell: rm -rf /usr/local/directadmin/custombuild/options.conf
  tags: [remove_conf_file]

- name: copy options.conf to /usr/local/directadmin/custombuild
  template: src=options.conf.j2 dest=/usr/local/directadmin/custombuild

- name: rename conf file
  shell: mv /usr/local/directadmin/custombuild/options.conf.j2 /usr/local/directadmin/custombuild/options.conf

- name: update DirectAdmin custombuild
  command: /usr/local/directadmin/custombuild/build all
  register: build_all


- debug:
    var: setup_output.stdout_lines
  when: directadmin_install

- debug:
    msg: "Directadmin is already installed and running, skipping.."
  when: not directadmin_install
